Revert "update appdata and add files"
This reverts commit e98267c0cd7887432ecf01e7a75720b5e8270be7.

diff --git a/biglinux-webapps/usr/bin/big-webapps-create b/biglinux-webapps/usr/bin/big-webapps-create
--- a/biglinux-webapps/usr/bin/big-webapps-create
+++ b/biglinux-webapps/usr/bin/big-webapps-create
@@ -25,22 +25,17 @@ display_help() {
     echo "    $0 create brave \"BigLinux\" \"https://www.biglinux.com.br\" \"big-logo\" \"Webapps\" \"Default\""
     echo ""
     echo "  Remove an existing WebApp:"
-    echo "    $0 remove brave-www.biglinux.com.br__-Default.desktop"
+    echo "    $0 remove brave \"https://www.biglinux.com.br\" \"Default\""
 }
+
+
+local_path=~/.local/share/applications
 
 # Check for minimum arguments
 if [ "$#" -lt 1 ]; then
     display_help
-    exit
+    exit 1
 fi
-
-# Check if the folder exists and create it if it doesn't
-if [[ ! -d ~/.local/share/applications ]]; then
-    mkdir -p ~/.local/share/applications
-fi
-
-# Change to the applications folder, if it fails, exit
-cd ~/.local/share/applications || { echo "Failed to change directory to ~/.local/share/applications"; exit 1; }
 
 # Main command
 command="$1"
@@ -48,37 +43,21 @@ shift
 
 if [[ $command == "json" ]]; then
     one_file="$1"
-
-# Remove
-elif [ $command == "remove" ]; then
-    if [ "$#" != "1" ]; then
-        display_help
-        exit 1
-    fi
-
-    filename="$1"
-
-    if [ -f $filename ]; then
-        rm $filename
-        echo "WebApp successfully removed!"
-        exit 0
-    else
-        echo "WebApp not found!"
-        exit 1
-    fi
-
 else
     # Set global variables
     browser="$1"
     name="$2"
     url="$3"
     icon="$4"
-    icon=${icon//*\/}
-    icon=${icon//\.*}
     category="$5"
     profile="$6"
 fi
 
+# Check if the folder exists and create it if it doesn't
+[[ ! -d $local_path ]] && mkdir -p $local_path
+
+# Change to the applications folder
+cd $local_path || return 1
 
 # Adjust the browser name for the filename and class
 short_browser=$(sed 's/.*[Cc]hrom.*/chrome/
@@ -93,17 +72,17 @@ class=$(sed 's|https://||;s|http://||g;s|/|__|g' <<< "$url")
 filename="$short_browser-$(sed 's|https://||;s|http://||;s|?.*||g;s|/|__|g' <<< $url)__-$profile.desktop"
 
 # Ensure filename doesn't end with more than two underscores and replace final __-profile with -profile
-filename=$(sed -E "s/(__.*)__-$profile/\1-$profile/g;s|__\@-|_@-|g" <<< "$filename")
+filename=$(sed -E "s/(__.*)__-$profile/\1-$profile/g" <<< "$filename")
 
 # Verify if the WebApp already exists
-if [[ -e ~/.local/share/applications/$filename ]]; then
+if [[ -e $local_path/$filename ]]; then
 
     # If the WebApp already exists, add BigWebApp1 or first available number
     i=1
     filename_orig=$filename
-    while [[ -e ~/.local/share/applications/$filename ]]; do
-        i=$((i + 1))
+    while [[ -e $local_path/$filename ]]; do
         filename="${filename_orig/.desktop/}-BigWebApp$i.desktop"
+        ((++i))
     done
 
 fi
@@ -124,7 +103,7 @@ Terminal=false
 Type=Application
 Name=$name
 Exec=filename="$filename" big-webapps-exec $browser --class="$class" --profile-directory=$profile --app="$url"
-Icon=${icon//*\/}
+Icon=$icon
 StartupWMClass=$class
 Categories=$category
 StartupNotify=false
@@ -147,6 +126,20 @@ elif [ "$command" = "verify" ]; then
     else
         echo "false"
         exit 0
+    fi
+
+# Remove
+elif [ "$command" = "remove" ]; then
+    if [ "$#" -ne 3 ]; then
+        display_help
+        exit 1
+    fi
+
+    if [ -f $filename ]; then
+        rm $filename
+        echo "WebApp successfully removed!"
+    else
+        echo "WebApp not found!"
     fi
 
 # List
@@ -178,7 +171,7 @@ elif [ "$command" = "json" ]; then
                     name=${line#*Name=}
                     ;;
                 "Exec="*)
-                    url=${line//*--app=}
+                    url=${line//*--app=\"}
                     url=${url//\"}
                     browser=${line//*big-webapps-exec }
                     browser=${browser// *}
@@ -187,19 +180,12 @@ elif [ "$command" = "json" ]; then
                     ;;
                 "Icon="*)
                     icon=${line#*Icon=}
-                    # Copy the icon to the applications folder if it's not a system icon
-                    if [[ $icon =~ / ]]; then
-                        cp "$icon" ~/.local/share/icons/
-                        sed -Ei 's|^Icon=.*/(.*)\..*|Icon=\1|g' "$file"
-                    fi
-                    icon=${icon//*\/}
-                    icon=${icon//\.*}
                     ;;
                 "Categories="*)
                     categories=${line#*Categories=}
                     ;;
             esac
-        done <<<$(grep -ve 'Name=Software Render' -ve 'Exec=SoftwareRender ' $file | grep -m4 -e '^Name=' -e '^Exec=' -e '^Icon=' -e '^Categories=')
+        done <<<$(grep -m4 -e '^Name=' -e '^Exec=' -e '^Icon=' -e '^Categories=' $file)
 
         # Print the JSON separator
         if [[ $num -gt 0 ]]; then
@@ -214,7 +200,6 @@ elif [ "$command" = "json" ]; then
                 "app_name": "${name//\"/\\\\\"}",
                 "app_url": "${url//\"/\\\\\"}",
                 "app_icon": "$icon",
-                "app_profile": "$profile",
                 "app_categories": "$categories"
             }
 EOF
